harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
envName: Production
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - -s4clJ0ISxyx11j5WBg0UQ
phases:
- type: KUBERNETES
  computeProviderName: Local K8s Cloud Provider
  daemonSet: false
  infraDefinitionName: prometheus
  name: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_CANARY_DEPLOY
      name: Canary Deployment
      properties:
        instanceUnitType: COUNT
        instances: '1'
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: PROMETHEUS
      name: Prometheus
      properties:
        analysisServerConfigId: MusUOwznQGSF4h4vXpHxmQ
        analysisTolerance: LOW
        comparisonStrategy: COMPARE_WITH_CURRENT
        customThresholdRefId: 1ce4caca99f34bbc935275f2aa53a820
        timeDuration: 5
        timeSeriesToAnalyze:
        - metricName: normal_call
          metricType: THROUGHPUT
          txnName: custom
          url: io_harness_custom_metric_normal_call{kubernetes_pod_name="$hostName"}
        - metricName: error_call
          metricType: ERROR
          txnName: custom
          url: io_harness_custom_metric_error_call{kubernetes_pod_name="$hostName"}
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    steps:
    - type: K8S_DELETE
      name: Canary Delete
      properties:
        instanceUnitType: COUNT
        resources: ${k8s.canaryWorkload}
    stepsInParallel: false
  provisionNodes: false
  serviceName: cvdeploy
  statefulSet: false
- type: KUBERNETES
  computeProviderName: Local K8s Cloud Provider
  daemonSet: false
  infraDefinitionName: prometheus
  name: Primary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: cvdeploy
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: Local K8s Cloud Provider
  daemonSet: false
  infraDefinitionName: prometheus
  name: Rollback Canary
  phaseNameForRollback: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DELETE
      name: Delete
      properties:
        deleteNamespacesForRelease: false
        resources: ${k8s.canaryWorkload}
        stateTimeoutInMinutes: 10
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: cvdeploy
  statefulSet: false
- type: KUBERNETES
  computeProviderName: Local K8s Cloud Provider
  daemonSet: false
  infraDefinitionName: prometheus
  name: Rollback Primary
  phaseNameForRollback: Primary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DEPLOYMENT_ROLLING_ROLLBACK
      name: Rollback Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: cvdeploy
  statefulSet: false
templatized: true
userVariables:
- type: TEXT
  fixed: false
  mandatory: false
  name: verify_canary
  value: 'yes'
- type: TEXT
  fixed: false
  mandatory: false
  name: metric_verification
  value: Prometheus
